spring:
  application:
    name: profile-service
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB_NAME}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        type_parameters: jsonb
    show-sql: true
server:
  port: 8080

app:
  internal:
    secret: ${X_INTERNAL_REQUEST_SECRET}
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    appname: profile-service
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

